// ─── 직접 매핑 (운동명 정확 일치) ──────────────────────────────────────────
// key: 소문자 영어 이름, value: 한국어 이름
export const EXERCISE_NAME_KO: Record<string, string> = {
  // ── Waist / 복근 ────────────────────────────────────────────────────
  '3/4 sit-up': '3/4 싯업',
  '45° side bend': '45도 사이드 벤드',
  'air bike': '에어 바이크',
  'alternate heel touchers': '얼터네이트 힐 터처',
  'cross body crunch': '크로스 바디 크런치',
  'crunch (hands overhead)': '크런치 (손 위)',
  'crunch (on stability ball)': '크런치 (짐볼)',
  'crunch (on stability ball, arms straight)': '크런치 (짐볼, 팔 뻗기)',
  'crunch floor': '플로어 크런치',
  'crunch': '크런치',
  'dead bug': '데드 버그',
  'decline crunch': '디클라인 크런치',
  'decline sit-up': '디클라인 싯업',
  'elbow-to-knee': '엘보우 투 니',
  'flutter kicks': '플러터 킥',
  'front plank with twist': '플랭크 트위스트',
  'groin crunch': '그로인 크런치',
  'hanging leg raise': '행잉 레그 레이즈',
  'hanging pike': '행잉 파이크',
  'hanging straight leg hip raise': '행잉 스트레이트 레그 힙 레이즈',
  'hanging straight leg raise': '행잉 스트레이트 레그 레이즈',
  'hanging straight twisting leg hip raise': '행잉 트위스팅 레그 레이즈',
  'hip raise (bent knee)': '힙 레이즈 (무릎 굽힘)',
  'hyperextension': '하이퍼익스텐션',
  'hyperextension (on bench)': '하이퍼익스텐션 (벤치)',
  'incline leg hip raise (leg straight)': '인클라인 레그 힙 레이즈',
  'incline twisting sit-up': '인클라인 트위스팅 싯업',
  'isometric wipers': '아이소메트릭 와이퍼',
  'jack burpee': '잭 버피',
  'jackknife sit-up': '잭나이프 싯업',
  'janda sit-up': '얀다 싯업',
  'kick out sit': '킥 아웃 싯',
  'leg pull in flat bench': '레그 풀인 (플랫 벤치)',
  'mountain climber': '마운틴 클라이머',
  'negative crunch': '네거티브 크런치',
  'oblique crunches floor': '오블리크 크런치',
  'otis up': '오티스 업',
  'reverse hyper extension (on stability ball)': '리버스 하이퍼익스텐션 (짐볼)',
  'russian twist': '러시안 트위스트',
  'seated leg raise': '시티드 레그 레이즈',
  'seated lower back stretch': '시티드 허리 스트레칭',
  'seated side crunch (wall)': '시티드 사이드 크런치 (벽)',
  'side bridge v. 2': '사이드 브리지',
  'sit-up v. 2': '싯업',
  'suspended abdominal fallout': '서스펜드 복근 폴아웃',
  'suspended reverse crunch': '서스펜드 리버스 크런치',
  'vertical leg raise (on parallel bars)': '버티컬 레그 레이즈 (평행봉)',

  // ── Back / 등 ────────────────────────────────────────────────────────
  'alternate lateral pulldown': '얼터네이트 레터럴 풀다운',
  'barbell bent over row': '바벨 벤트오버 로우',
  'barbell deadlift': '바벨 데드리프트',
  'barbell good morning': '바벨 굿모닝',
  'barbell incline row': '바벨 인클라인 로우',
  'barbell one arm bent over row': '바벨 원암 벤트오버 로우',
  'barbell one arm side deadlift': '바벨 원암 사이드 데드리프트',
  'barbell pullover': '바벨 풀오버',
  'barbell pullover to press': '바벨 풀오버 투 프레스',
  'barbell rack pull': '바벨 랙풀',
  'barbell rear delt raise': '바벨 리어 델트 레이즈',
  'barbell rear delt row': '바벨 리어 델트 로우',
  'barbell reverse grip bent over row': '바벨 리버스그립 벤트오버 로우',
  'barbell romanian deadlift': '바벨 루마니안 데드리프트',
  'barbell straight leg deadlift': '바벨 스트레이트 레그 데드리프트',
  'barbell sumo deadlift': '바벨 스모 데드리프트',
  'barbell upright row': '바벨 업라이트 로우',
  'barbell wide-grip upright row': '바벨 와이드그립 업라이트 로우',
  'biceps narrow pull-ups': '바이셉스 내로우 풀업',
  'biceps pull-up': '바이셉스 풀업',
  'cambered bar lying row': '캠버드 바 라잉 로우',
  'chin-ups (narrow parallel grip)': '내로우 패럴렐그립 친업',
  'gironda sternum chin': '지론다 스터넘 친',
  'gorilla chin': '고릴라 친업',
  'inverted row': '인버티드 로우',
  'inverted row v. 2': '인버티드 로우 v.2',
  'inverted row with straps': '스트랩 인버티드 로우',
  'kipping muscle up': '킵핑 머슬업',
  'mixed grip chin-up': '믹스드 그립 친업',
  'muscle up': '머슬업',
  'one arm chin-up': '원암 친업',
  'pull up (neutral grip)': '뉴트럴그립 풀업',
  'pull-up': '풀업',
  'rear pull-up': '리어 풀업',
  'reverse grip pull-up': '리버스그립 풀업',
  'ring dips': '링 딥스',
  'rocky pull-up pulldown': '로키 풀업 풀다운',
  'rope climb': '로프 클라임',
  'scapular pull-up': '스캐퓰러 풀업',
  'side-to-side chin': '사이드 투 사이드 친업',
  'suspended row': '서스펜드 로우',
  'trap bar deadlift': '트랩바 데드리프트',
  'twin handle parallel grip lat pulldown': '트윈 핸들 패럴렐그립 랫풀다운',

  // ── Chest / 가슴 ─────────────────────────────────────────────────────
  'assisted chest dip (kneeling)': '어시스티드 체스트 딥 (닐링)',
  'barbell bench press': '바벨 벤치프레스',
  'barbell close-grip bench press': '바벨 클로즈그립 벤치프레스',
  'barbell decline bench press': '바벨 디클라인 벤치프레스',
  'barbell decline wide-grip press': '바벨 디클라인 와이드그립 프레스',
  'barbell guillotine bench press': '바벨 길로틴 벤치프레스',
  'barbell incline bench press': '바벨 인클라인 벤치프레스',
  'barbell incline reverse-grip press': '바벨 인클라인 리버스그립 프레스',
  'barbell jm bench press': '바벨 JM 벤치프레스',
  'barbell lying close-grip press': '바벨 라잉 클로즈그립 프레스',
  'barbell one arm floor press': '바벨 원암 플로어 프레스',
  'barbell wide bench press': '바벨 와이드 벤치프레스',
  'bench dip (knees bent)': '벤치 딥 (무릎 굽힘)',
  'chest dip': '체스트 딥',
  'clock push-up': '클락 푸시업',
  'close-grip push-up': '클로즈그립 푸시업',
  'decline push-up': '디클라인 푸시업',
  'diamond push-up': '다이아몬드 푸시업',
  'dumbbell bench press': '덤벨 벤치프레스',
  'dumbbell close-grip press': '덤벨 클로즈그립 프레스',
  'dumbbell decline bench press': '덤벨 디클라인 벤치프레스',
  'dumbbell decline fly': '덤벨 디클라인 플라이',
  'dumbbell decline hammer press': '덤벨 디클라인 해머프레스',
  'dumbbell decline twist fly': '덤벨 디클라인 트위스트 플라이',
  'dumbbell fly': '덤벨 플라이',
  'dumbbell incline bench press': '덤벨 인클라인 벤치프레스',
  'dumbbell incline fly': '덤벨 인클라인 플라이',
  'dumbbell incline hammer press': '덤벨 인클라인 해머프레스',
  'dumbbell incline twisted flyes': '덤벨 인클라인 트위스티드 플라이',
  'dumbbell iron cross': '덤벨 아이언 크로스',
  'dumbbell straight arm pullover': '덤벨 스트레이트 암 풀오버',
  'floor fly (with barbell)': '플로어 플라이 (바벨)',
  'incline close-grip push-up': '인클라인 클로즈그립 푸시업',
  'incline push up depth jump': '인클라인 뎁스 점프 푸시업',
  'incline push-up': '인클라인 푸시업',
  'incline reverse grip push-up': '인클라인 리버스그립 푸시업',
  'outside leg kick push-up': '아웃사이드 레그 킥 푸시업',
  'push-up': '푸시업',
  'push-up (bosu ball)': '푸시업 (보수볼)',
  'push-up (on stability ball)': '푸시업 (짐볼)',
  'push-up (wall)': '푸시업 (벽)',
  'push-up (wall) v. 2': '푸시업 (벽) v.2',
  'push-up close-grip off dumbbell': '덤벨 클로즈그립 푸시업',
  'push-up inside leg kick': '인사이드 레그 킥 푸시업',
  'push-up medicine ball': '메디신볼 푸시업',
  'push-up to side plank': '푸시업 투 사이드 플랭크',
  'raise single arm push-up': '원암 레이즈 푸시업',
  'reverse dip': '리버스 딥',
  'shoulder tap push-up': '숄더 탭 푸시업',
  'side push-up': '사이드 푸시업',
  'single arm push-up': '원암 푸시업',
  'spider crawl push up': '스파이더 크롤 푸시업',
  'superman push-up': '슈퍼맨 푸시업',
  'suspended push-up': '서스펜드 푸시업',
  'weighted svend press': '웨이티드 스벤드 프레스',

  // ── Shoulders / 어깨 ─────────────────────────────────────────────────
  'barbell clean and press': '바벨 클린앤프레스',
  'barbell front raise': '바벨 프론트 레이즈',
  'barbell front raise and pullover': '바벨 프론트 레이즈 앤 풀오버',
  'barbell incline shoulder raise': '바벨 인클라인 숄더 레이즈',
  'barbell seated behind head military press': '바벨 시티드 비하인드넥 밀리터리프레스',
  'barbell seated bradford rocky press': '바벨 브래드포드 프레스',
  'barbell seated overhead press': '바벨 시티드 오버헤드프레스',
  'barbell shrug': '바벨 슈러그',
  'dumbbell alternate side press': '덤벨 얼터네이트 사이드 프레스',
  'dumbbell arnold press v. 2': '덤벨 아놀드프레스',
  'dumbbell front raise': '덤벨 프론트 레이즈',
  'dumbbell full can lateral raise': '덤벨 풀캔 레터럴 레이즈',
  'dumbbell incline one arm lateral raise': '덤벨 인클라인 원암 레터럴 레이즈',
  'dumbbell incline rear lateral raise': '덤벨 인클라인 리어 레터럴 레이즈',
  'dumbbell incline shoulder raise': '덤벨 인클라인 숄더 레이즈',
  'dumbbell lateral raise': '덤벨 레터럴 레이즈',
  'dumbbell lateral to front raise': '덤벨 레터럴 투 프론트 레이즈',
  'dumbbell side lying one hand raise': '덤벨 사이드 라잉 원핸드 레이즈',
  'dumbbell standing alternate overhead press': '덤벨 얼터네이트 오버헤드프레스',
  'dumbbell standing alternate raise': '덤벨 얼터네이트 레이즈',
  'dumbbell standing overhead press': '덤벨 오버헤드프레스',
  'dumbbell upright row': '덤벨 업라이트 로우',
  'dumbbell w-press': '덤벨 W-프레스',
  'handstand push-up': '물구나무서기 푸시업',
  'landmine 180': '랜드마인 180',
  'power clean': '파워 클린',
  'rear decline bridge': '리어 디클라인 브리지',
  'rear deltoid stretch': '리어 델토이드 스트레칭',
  'side hip (on parallel bars)': '사이드 힙 (평행봉)',
  'side push neck stretch': '사이드 넥 스트레칭',
  'snatch pull': '스내치 풀',
  'spell caster': '스펠 캐스터',
  'squat jerk': '스쿼트 저크',
  'standing behind neck press': '비하인드넥 프레스',
  'standing lateral stretch': '스탠딩 레터럴 스트레칭',

  // ── Upper Arms / 팔 ──────────────────────────────────────────────────
  'assisted standing triceps extension (with towel)': '어시스티드 트라이셉스 익스텐션 (수건)',
  'assisted triceps dip (kneeling)': '어시스티드 트라이셉스 딥 (닐링)',
  'barbell alternate biceps curl': '바벨 얼터네이트 바이셉스 컬',
  'barbell curl': '바벨 컬',
  'barbell drag curl': '바벨 드래그 컬',
  'barbell lying close-grip triceps extension': '바벨 라잉 클로즈그립 트라이셉스 익스텐션',
  'barbell lying extension': '바벨 라잉 익스텐션',
  'barbell lying preacher curl': '바벨 라잉 프리처 컬',
  'barbell lying triceps extension': '바벨 스컬 크러셔',
  'barbell lying triceps extension skull crusher': '바벨 스컬 크러셔',
  'barbell overhead standing triceps extension': '바벨 오버헤드 트라이셉스 익스텐션',
  'barbell preacher curl': '바벨 프리처 컬',
  'barbell prone incline curl': '바벨 프론 인클라인 컬',
  'barbell reverse curl': '바벨 리버스 컬',
  'barbell seated close-grip concentration curl': '바벨 시티드 컨센트레이션 컬',
  'barbell seated overhead triceps extension': '바벨 시티드 오버헤드 트라이셉스 익스텐션',
  'barbell standing close grip curl': '바벨 클로즈그립 컬',
  'barbell standing overhead triceps extension': '바벨 스탠딩 오버헤드 트라이셉스 익스텐션',
  'barbell standing reverse grip curl': '바벨 리버스그립 스탠딩 컬',
  'barbell standing wide-grip curl': '바벨 와이드그립 컬',
  'body-up': '바디업',
  'bottoms-up': '바텀스업',
  'dumbbell alternate biceps curl': '덤벨 얼터네이트 바이셉스 컬',
  'dumbbell biceps curl': '덤벨 바이셉스 컬',
  'dumbbell concentration curl': '덤벨 컨센트레이션 컬',
  'dumbbell cross body hammer curl': '덤벨 크로스바디 해머 컬',
  'dumbbell decline triceps extension': '덤벨 디클라인 트라이셉스 익스텐션',
  'dumbbell hammer curl': '덤벨 해머 컬',
  'dumbbell incline biceps curl': '덤벨 인클라인 바이셉스 컬',
  'dumbbell incline curl': '덤벨 인클라인 컬',
  'dumbbell incline hammer curl': '덤벨 인클라인 해머 컬',
  'dumbbell incline inner biceps curl': '덤벨 인클라인 이너 바이셉스 컬',
  'dumbbell kickback': '덤벨 킥백',
  'dumbbell standing concentration curl': '덤벨 스탠딩 컨센트레이션 컬',
  'dumbbell standing kickback': '덤벨 스탠딩 킥백',
  'dumbbell standing one arm concentration curl': '덤벨 원암 컨센트레이션 컬',
  'dumbbell standing one arm extension': '덤벨 원암 익스텐션',
  'dumbbell standing one arm reverse curl': '덤벨 원암 리버스 컬',
  'dumbbell standing preacher curl': '덤벨 스탠딩 프리처 컬',
  'dumbbell standing reverse curl': '덤벨 리버스 컬',
  'dumbbell standing triceps extension': '덤벨 스탠딩 트라이셉스 익스텐션',
  'dumbbell tate press': '덤벨 테이트 프레스',
  'dumbbell zottman curl': '덤벨 조트만 컬',
  'ez barbell anti gravity press': 'EZ바 안티그래비티 프레스',
  'ez barbell close-grip curl': 'EZ바 클로즈그립 컬',
  'ez barbell curl': 'EZ바 컬',
  'ez barbell decline close grip face press': 'EZ바 디클라인 클로즈그립 페이스 프레스',
  'ez barbell incline triceps extension': 'EZ바 인클라인 트라이셉스 익스텐션',
  'ez barbell jm bench press': 'EZ바 JM 벤치프레스',
  'ez barbell reverse grip curl': 'EZ바 리버스그립 컬',
  'ez barbell reverse grip preacher curl': 'EZ바 리버스그립 프리처 컬',
  'ez barbell seated triceps extension': 'EZ바 시티드 트라이셉스 익스텐션',
  'ez barbell spider curl': 'EZ바 스파이더 컬',
  'olympic barbell hammer curl': '올림픽 바벨 해머 컬',
  'olympic barbell triceps extension': '올림픽 바벨 트라이셉스 익스텐션',
  'one arm dip': '원암 딥',
  'overhead triceps stretch': '오버헤드 트라이셉스 스트레칭',
  'triceps dip': '트라이셉스 딥',
  'triceps dip (bench leg)': '트라이셉스 딥 (벤치)',
  'triceps dip (between benches)': '트라이셉스 딥 (벤치 사이)',
  'triceps dips floor': '트라이셉스 딥 (플로어)',
  'triceps press': '트라이셉스 프레스',
  'triceps stretch': '트라이셉스 스트레칭',
  'weighted bench dip': '웨이티드 벤치 딥',
  'weighted seated bicep curl (on stability ball)': '웨이티드 바이셉스 컬 (짐볼)',
  'weighted standing curl': '웨이티드 스탠딩 컬',

  // ── Lower Arms / 팔뚝 ────────────────────────────────────────────────
  'barbell reverse wrist curl': '바벨 리버스 리스트 컬',
  'barbell standing back wrist curl': '바벨 스탠딩 백 리스트 컬',
  'barbell wrist curl': '바벨 리스트 컬',
  'finger curls': '핑거 컬',
  'weighted standing hand squeeze': '웨이티드 핸드 스퀴즈',

  // ── Upper Legs / 허벅지 ──────────────────────────────────────────────
  'barbell bench front squat': '바벨 벤치 프론트 스쿼트',
  'barbell bench squat': '바벨 벤치 스쿼트',
  'barbell clean-grip front squat': '바벨 클린그립 프론트 스쿼트',
  'barbell front chest squat': '바벨 프론트 체스트 스쿼트',
  'barbell front squat': '바벨 프론트 스쿼트',
  'barbell full squat': '바벨 풀 스쿼트',
  'barbell hack squat': '바벨 핵 스쿼트',
  'barbell jefferson squat': '바벨 제퍼슨 스쿼트',
  'barbell jump squat': '바벨 점프 스쿼트',
  'barbell lunge': '바벨 런지',
  'barbell narrow stance squat': '바벨 내로우스탠스 스쿼트',
  'barbell one leg squat': '바벨 원레그 스쿼트',
  'barbell overhead squat': '바벨 오버헤드 스쿼트',
  'barbell rear lunge': '바벨 리어 런지',
  'barbell side split squat': '바벨 사이드 스플릿 스쿼트',
  'barbell single leg split squat': '바벨 싱글 레그 스플릿 스쿼트',
  'barbell speed squat': '바벨 스피드 스쿼트',
  'barbell squat (on knees)': '바벨 무릎 스쿼트',
  'barbell step-up': '바벨 스텝업',
  'barbell stiff leg good morning': '바벨 스티프 레그 굿모닝',
  'barbell wide squat': '바벨 와이드 스쿼트',
  'barbell zercher squat': '바벨 저처 스쿼트',
  'bench hip extension': '벤치 힙 익스텐션',
  'circles knee stretch': '서클 무릎 스트레칭',
  'donkey calf raise': '동키 카프 레이즈',
  'dumbbell bench squat': '덤벨 벤치 스쿼트',
  'dumbbell romanian deadlift': '덤벨 루마니안 데드리프트 (누락)',
  'dumbbell single leg split squat': '덤벨 싱글 레그 스플릿 스쿼트',
  'dumbbell single leg squat': '덤벨 싱글 레그 스쿼트',
  'dumbbell squat': '덤벨 스쿼트',
  'dumbbell standing calf raise': '덤벨 스탠딩 카프 레이즈',
  'dumbbell step-up': '덤벨 스텝업',
  'dumbbell stiff leg deadlift': '덤벨 스티프 레그 데드리프트',
  'dumbbell straight leg deadlift': '덤벨 스트레이트 레그 데드리프트',
  'flexion leg sit up (bent knee)': '플렉션 레그 싯업 (무릎 굽힘)',
  'flexion leg sit up (straight arm)': '플렉션 레그 싯업 (팔 뻗기)',
  'inverse leg curl (bench support)': '인버스 레그 컬 (벤치 지지)',
  'jump squat': '점프 스쿼트',
  'jump squat v. 2': '점프 스쿼트 v.2',
  'lying (side) quads stretch': '라잉 쿼드 스트레칭',
  'march sit (wall)': '마치 싯 (벽)',
  'monster walk': '몬스터 워크',
  'self assisted inverse leg curl': '셀프 어시스티드 인버스 레그 컬',
  'self assisted inverse leg curl (on floor)': '셀프 어시스티드 인버스 레그 컬 (플로어)',
  'single leg calf raise (on a dumbbell)': '싱글 레그 카프 레이즈 (덤벨)',
  'single leg platform slide': '싱글 레그 플랫폼 슬라이드',
  'sled 45° calf press': '슬레드 45도 카프 프레스',
  'sled 45° leg press': '슬레드 45도 레그프레스',
  'sled 45° leg wide press': '슬레드 45도 와이드 레그프레스',
  'sled closer hack squat': '슬레드 핵 스쿼트',
  'sled forward angled calf raise': '슬레드 포워드 카프 레이즈',
  'sled hack squat': '슬레드 핵 스쿼트',
  'sled lying squat': '슬레드 라잉 스쿼트',
  'standing single leg curl': '스탠딩 싱글 레그 컬',
  'weighted donkey calf raise': '웨이티드 동키 카프 레이즈',
  'weighted sissy squat': '웨이티드 시시 스쿼트',
  'weighted squat': '웨이티드 스쿼트',

  // ── Lower Legs / 종아리 ──────────────────────────────────────────────
  'barbell seated calf raise': '바벨 시티드 카프 레이즈',
  'barbell standing leg calf raise': '바벨 스탠딩 카프 레이즈',
  'barbell standing rocking leg calf raise': '바벨 로킹 카프 레이즈',
  'dumbbell single leg calf raise': '덤벨 싱글 레그 카프 레이즈',

  // ── Cardio / 유산소 ──────────────────────────────────────────────────
  'balance board': '밸런스 보드',
  'battling ropes': '배틀 로프',
  'run': '달리기',
  'run (equipment)': '러닝 (기구)',
  'stationary bike walk': '고정식 자전거',
  'wind sprints': '윈드 스프린트',

  // ── Neck / 목 ────────────────────────────────────────────────────────
  'side hip abduction': '사이드 힙 어브덕션',
  'side wrist pull stretch': '사이드 리스트 풀 스트레칭',

  // ── Kettlebell ───────────────────────────────────────────────────────
  'kettlebell advanced windmill': '케틀벨 어드밴스드 윈드밀',
  'kettlebell alternating hang clean': '케틀벨 얼터네이팅 행 클린',
  'kettlebell alternating press': '케틀벨 얼터네이팅 프레스',
  'kettlebell alternating press on floor': '케틀벨 얼터네이팅 플로어 프레스',
  'kettlebell alternating renegade row': '케틀벨 레니게이드 로우',
  'kettlebell alternating row': '케틀벨 얼터네이팅 로우',
  'kettlebell arnold press': '케틀벨 아놀드프레스',
  'kettlebell bent press': '케틀벨 벤트 프레스',
  'kettlebell double jerk': '케틀벨 더블 저크',
  'kettlebell double push press': '케틀벨 더블 푸시프레스',
  'kettlebell double snatch': '케틀벨 더블 스내치',
  'kettlebell double windmill': '케틀벨 더블 윈드밀',
  'kettlebell figure 8': '케틀벨 피겨8',
  'kettlebell front squat': '케틀벨 프론트 스쿼트',
  'kettlebell goblet squat': '케틀벨 고블렛 스쿼트',
  'kettlebell hang clean': '케틀벨 행 클린',
  'kettlebell lunge pass through': '케틀벨 런지 패스스루',
  'kettlebell one arm clean and jerk': '케틀벨 원암 클린앤저크',
  'kettlebell one arm jerk': '케틀벨 원암 저크',
  'kettlebell one arm military press to the side': '케틀벨 원암 사이드 밀리터리프레스',
  'kettlebell one arm push press': '케틀벨 원암 푸시프레스',
  'kettlebell one arm row': '케틀벨 원암 로우',
  'kettlebell one arm snatch': '케틀벨 원암 스내치',
  'kettlebell pistol squat': '케틀벨 피스톨 스쿼트',
  'kettlebell plyo push-up': '케틀벨 플라이오 푸시업',
  'kettlebell seated press': '케틀벨 시티드 프레스',
  'kettlebell seesaw press': '케틀벨 시소 프레스',
  'kettlebell sumo high pull': '케틀벨 스모 하이풀',
  'kettlebell swing': '케틀벨 스윙',
  'kettlebell thruster': '케틀벨 스러스터',
  'kettlebell turkish get up (squat style)': '케틀벨 터키시 겟업',
  'kettlebell two arm clean': '케틀벨 투암 클린',
  'kettlebell two arm military press': '케틀벨 투암 밀리터리프레스',
  'kettlebell windmill': '케틀벨 윈드밀',

  // ── Lever (머신) ─────────────────────────────────────────────────────
  'lever alternating narrow grip seated row': '머신 내로우그립 시티드 로우',
  'lever assisted chin-up': '어시스티드 친업 (머신)',
  'lever back extension': '백 익스텐션 (머신)',
  'lever bent over row': '벤트오버 로우 (머신)',
  'lever bicep curl': '바이셉스 컬 (머신)',
  'lever chest press': '체스트프레스 (머신)',
  'lever deadlift': '데드리프트 (머신)',
  'lever front pulldown': '프론트 풀다운 (머신)',
  'lever gripless shrug': '그립리스 슈러그 (머신)',
  'lever high row': '하이 로우 (머신)',
  'lever kneeling leg curl': '닐링 레그 컬 (머신)',
  'lever kneeling twist': '닐링 트위스트 (머신)',
  'lever lateral raise': '레터럴 레이즈 (머신)',
  'lever leg extension': '레그 익스텐션 (머신)',
  'lever lying leg curl': '라잉 레그 컬 (머신)',
  'lever military press': '밀리터리프레스 (머신)',
  'lever narrow grip seated row': '내로우그립 시티드 로우 (머신)',
  'lever one arm bent over row': '원암 벤트오버 로우 (머신)',
  'lever one arm shoulder press': '원암 숄더프레스 (머신)',
  'lever overhand triceps dip': '오버핸드 트라이셉스 딥 (머신)',
  'lever preacher curl': '프리처 컬 (머신)',
  'lever reverse hyperextension': '리버스 하이퍼익스텐션 (머신)',
  'lever seated calf raise': '시티드 카프 레이즈 (머신)',
  'lever seated crunch (chest pad)': '시티드 크런치 (머신)',
  'lever seated fly': '시티드 플라이 (머신)',
  'lever seated hip abduction': '힙 어브덕션 (머신)',
  'lever seated hip adduction': '힙 어덕션 (머신)',
  'lever seated leg curl': '시티드 레그 컬 (머신)',
  'lever seated leg raise crunch': '시티드 레그 레이즈 크런치 (머신)',
  'lever seated reverse fly': '시티드 리어 플라이 (머신)',
  'lever seated reverse fly (parallel grip)': '시티드 리어 플라이 패럴렐그립 (머신)',
  'lever shoulder press': '숄더프레스 (머신)',
  'lever shrug': '슈러그 (머신)',
  'lever standing calf raise': '스탠딩 카프 레이즈 (머신)',
  'lever t bar row': 'T바 로우 (머신)',
  'lever triceps extension': '트라이셉스 익스텐션 (머신)',

  // ── Smith Machine ────────────────────────────────────────────────────
  'smith back shrug': '스미스 백 슈러그',
  'smith behind neck press': '스미스 비하인드넥 프레스',
  'smith bench press': '스미스 벤치프레스',
  'smith bent knee good morning': '스미스 굿모닝',
  'smith chair squat': '스미스 체어 스쿼트',
  'smith close-grip bench press': '스미스 클로즈그립 벤치프레스',
  'smith deadlift': '스미스 데드리프트',
  'smith decline bench press': '스미스 디클라인 벤치프레스',
  'smith decline reverse-grip press': '스미스 디클라인 리버스그립 프레스',
  'smith hack squat': '스미스 핵 스쿼트',
  'smith hip raise': '스미스 힙 레이즈',
  'smith incline bench press': '스미스 인클라인 벤치프레스',
  'smith incline reverse-grip press': '스미스 인클라인 리버스그립 프레스',
  'smith incline shoulder raises': '스미스 인클라인 숄더 레이즈',
  'smith leg press': '스미스 레그프레스',
  'smith narrow row': '스미스 내로우 로우',
  'smith rear delt row': '스미스 리어 델트 로우',
  'smith reverse calf raises': '스미스 리버스 카프 레이즈',
  'smith reverse-grip press': '스미스 리버스그립 프레스',
  'smith seated shoulder press': '스미스 시티드 숄더프레스',
  'smith shoulder press': '스미스 숄더프레스',
  'smith shrug': '스미스 슈러그',
  'smith single leg split squat': '스미스 싱글 레그 스플릿 스쿼트',
  'smith sprint lunge': '스미스 스프린트 런지',
  'smith squat': '스미스 스쿼트',
  'smith standing back wrist curl': '스미스 스탠딩 백 리스트 컬',
  'smith standing behind head military press': '스미스 비하인드헤드 밀리터리프레스',
  'smith standing leg calf raise': '스미스 스탠딩 카프 레이즈',
  'smith standing military press': '스미스 밀리터리프레스',
  'smith upright row': '스미스 업라이트 로우',

  // ── Cable ────────────────────────────────────────────────────────────
  'cable alternate shoulder press': '케이블 얼터네이트 숄더프레스',
  'cable alternate triceps extension': '케이블 얼터네이트 트라이셉스 익스텐션',
  'cable bar lateral pulldown': '케이블 바 레터럴 풀다운',
  'cable bench press': '케이블 벤치프레스',
  'cable deadlift': '케이블 데드리프트',
  'cable decline fly': '케이블 디클라인 플라이',
  'cable floor seated wide-grip row': '케이블 플로어 와이드그립 시티드 로우',
  'cable forward raise': '케이블 포워드 레이즈',
  'cable front raise': '케이블 프론트 레이즈',
  'cable front shoulder raise': '케이블 프론트 숄더 레이즈',
  'cable hammer curl (with rope)': '케이블 해머 컬 (로프)',
  'cable high row (kneeling)': '케이블 하이 로우 (닐링)',
  'cable hip adduction': '케이블 힙 어덕션',
  'cable incline bench press': '케이블 인클라인 벤치프레스',
  'cable incline fly': '케이블 인클라인 플라이',
  'cable incline pushdown': '케이블 인클라인 푸시다운',
  'cable incline triceps extension': '케이블 인클라인 트라이셉스 익스텐션',
  'cable kneeling crunch': '케이블 닐링 크런치',
  'cable kneeling triceps extension': '케이블 닐링 트라이셉스 익스텐션',
  'cable lateral pulldown (with rope attachment)': '케이블 레터럴 풀다운 (로프)',
  'cable lateral raise': '케이블 레터럴 레이즈',
  'cable low fly': '케이블 로우 플라이',
  'cable low seated row': '케이블 로우 시티드 로우',
  'cable lying fly': '케이블 라잉 플라이',
  'cable middle fly': '케이블 미들 플라이',
  'cable one arm bent over row': '케이블 원암 벤트오버 로우',
  'cable one arm curl': '케이블 원암 컬',
  'cable one arm lateral bent-over': '케이블 원암 레터럴 벤트오버',
  'cable one arm lateral raise': '케이블 원암 레터럴 레이즈',
  'cable one arm straight back high row (kneeling)': '케이블 원암 하이 로우 (닐링)',
  'cable overhead triceps extension (rope attachment)': '케이블 오버헤드 트라이셉스 익스텐션 (로프)',
  'cable preacher curl': '케이블 프리처 컬',
  'cable pull through (with rope)': '케이블 풀스루 (로프)',
  'cable pulldown': '케이블 풀다운',
  'cable pulldown (pro lat bar)': '케이블 풀다운 (프로 랫바)',
  'cable pushdown': '케이블 푸시다운',
  'cable pushdown (with rope attachment)': '케이블 푸시다운 (로프)',
  'cable rear delt row (stirrups)': '케이블 리어 델트 로우',
  'cable rear delt row (with rope)': '케이블 리어 델트 로우 (로프)',
  'cable rear drive': '케이블 리어 드라이브',
  'cable rear pulldown': '케이블 리어 풀다운',
  'cable reverse curl': '케이블 리버스 컬',
  'cable reverse preacher curl': '케이블 리버스 프리처 컬',
  'cable reverse wrist curl': '케이블 리버스 리스트 컬',
  'cable reverse-grip pushdown': '케이블 리버스그립 푸시다운',
  'cable reverse-grip straight back seated high row': '케이블 리버스그립 하이 로우',
  'cable russian twists (on stability ball)': '케이블 러시안 트위스트 (짐볼)',
  'cable seated crunch': '케이블 시티드 크런치',
  'cable seated high row (v-bar)': '케이블 시티드 하이 로우 (V바)',
  'cable seated one arm alternate row': '케이블 원암 얼터네이트 로우',
  'cable seated rear lateral raise': '케이블 시티드 리어 레터럴 레이즈',
  'cable seated wide-grip row': '케이블 와이드그립 시티드 로우',
  'cable shoulder press': '케이블 숄더프레스',
  'cable shrug': '케이블 슈러그',
  'cable side bend': '케이블 사이드 벤드',
  'cable side crunch': '케이블 사이드 크런치',
  'cable standing crunch': '케이블 스탠딩 크런치',
  'cable standing fly': '케이블 스탠딩 플라이',
  'cable standing hip extension': '케이블 스탠딩 힙 익스텐션',
  'cable standing one arm triceps extension': '케이블 원암 트라이셉스 익스텐션',
  'cable standing pulldown (with rope)': '케이블 스탠딩 풀다운 (로프)',
  'cable standing rear delt row (with rope)': '케이블 스탠딩 리어 델트 로우',
  'cable standing row (v-bar)': '케이블 스탠딩 로우 (V바)',
  'cable straight arm pulldown': '케이블 스트레이트 암 풀다운',
  'cable straight arm pulldown (with rope)': '케이블 스트레이트 암 풀다운 (로프)',
  'cable straight back seated row': '케이블 스트레이트백 시티드 로우',
  'cable triceps pushdown (v-bar)': '케이블 트라이셉스 푸시다운 (V바)',
  'cable tuck reverse crunch': '케이블 터크 리버스 크런치',
  'cable twist': '케이블 트위스트',
  'cable twisting pull': '케이블 트위스팅 풀',
  'cable underhand pulldown': '케이블 언더핸드 풀다운',
  'cable upright row': '케이블 업라이트 로우',
  'cable wrist curl': '케이블 리스트 컬',

  // ── Misc / 기타 ──────────────────────────────────────────────────────
  'assisted hanging knee raise': '어시스티드 행잉 니 레이즈',
  'assisted hanging knee raise with throw down': '어시스티드 행잉 니 레이즈 with 스로다운',
  'assisted lying leg raise with lateral throw down': '어시스티드 라잉 레그 레이즈 with 레터럴 스로다운',
  'assisted lying leg raise with throw down': '어시스티드 라잉 레그 레이즈 with 스로다운',
  'assisted motion russian twist': '어시스티드 러시안 트위스트',
  'assisted parallel close grip pull-up': '어시스티드 패럴렐 클로즈그립 풀업',
  'assisted prone hamstring': '어시스티드 프론 햄스트링',
  'assisted pull-up': '어시스티드 풀업',
  'barbell skier': '바벨 스키어',
  'barbell standing ab rollerout': '바벨 스탠딩 복근 롤아웃',
  'barbell standing bradford press': '바벨 브래드포드 프레스',
  'barbell standing front raise over head': '바벨 오버헤드 프론트 레이즈',
  'barbell standing twist': '바벨 스탠딩 트위스트',
  'standing wheel rollerout': '스탠딩 휠 롤아웃',
  'wheel rollout': '휠 롤아웃',
  'weighted crunch': '웨이티드 크런치',
  'weighted front raise': '웨이티드 프론트 레이즈',
  'weighted hyperextension (on stability ball)': '웨이티드 하이퍼익스텐션 (짐볼)',
  'weighted overhead crunch (on stability ball)': '웨이티드 오버헤드 크런치 (짐볼)',
  'weighted pull-up': '웨이티드 풀업',
  'weighted round arm': '웨이티드 라운드 암',
  'weighted russian twist': '웨이티드 러시안 트위스트',
  'weighted russian twist (legs up)': '웨이티드 러시안 트위스트 (다리 올림)',
  'weighted seated twist (on stability ball)': '웨이티드 시티드 트위스트 (짐볼)',
  'weighted side bend (on stability ball)': '웨이티드 사이드 벤드 (짐볼)',
};

// ─── bodyPart 매핑 ──────────────────────────────────────────────────────────
export const BODY_PART_KO: Record<string, string> = {
  chest: '가슴',
  back: '등',
  shoulders: '어깨',
  'upper arms': '팔',
  'lower arms': '팔뚝',
  'upper legs': '허벅지',
  'lower legs': '종아리',
  waist: '복근',
  cardio: '유산소',
  neck: '목',
};

// ─── equipment 매핑 ─────────────────────────────────────────────────────────
export const EQUIPMENT_KO: Record<string, string> = {
  barbell: '바벨',
  dumbbell: '덤벨',
  cable: '케이블',
  'body weight': '맨몸',
  'body weight (with resistance band)': '밴드',
  machine: '머신',
  kettlebell: '케틀벨',
  'resistance band': '밴드',
  'leverage machine': '레버리지 머신',
  'smith machine': '스미스 머신',
  'ez barbell': 'EZ바',
  'olympic barbell': '올림픽 바벨',
  'trap bar': '트랩바',
  rope: '로프',
  'medicine ball': '메디신볼',
  'stability ball': '짐볼',
  'bosu ball': '보수볼',
  'sled machine': '슬레드',
  'wheel roller': '휠 롤러',
  assisted: '보조',
  'assisted (towel)': '수건 보조',
  weighted: '무게 추가',
};

// ─── difficulty 매핑 ────────────────────────────────────────────────────────
export const DIFFICULTY_KO: Record<string, string> = {
  beginner: '초급',
  intermediate: '중급',
  advanced: '고급',
  expert: '고급',
};

// ─── target muscle 매핑 ─────────────────────────────────────────────────────
export const TARGET_KO: Record<string, string> = {
  abs: '복근',
  abductors: '외전근',
  adductors: '내전근',
  biceps: '이두근',
  calves: '종아리',
  'cardiovascular system': '심폐',
  delts: '삼각근',
  forearms: '전완근',
  glutes: '둔근',
  hamstrings: '햄스트링',
  lats: '광배근',
  'levator scapulae': '견갑거근',
  pectorals: '대흉근',
  quads: '대퇴사두근',
  'serratus anterior': '전거근',
  spine: '척추기립근',
  traps: '승모근',
  triceps: '삼두근',
  'upper back': '상부 등',
};

// ─── 단어 단위 번역 (직접 매핑에 없는 운동 fallback) ──────────────────────
const WORD_MAP: Record<string, string> = {
  barbell: '바벨',
  dumbbell: '덤벨',
  cable: '케이블',
  kettlebell: '케틀벨',
  smith: '스미스',
  lever: '머신',
  'ez barbell': 'EZ바',
  weighted: '웨이티드',
  assisted: '어시스티드',
  suspended: '서스펜드',
  bench: '벤치',
  incline: '인클라인',
  decline: '디클라인',
  seated: '시티드',
  standing: '스탠딩',
  lying: '라잉',
  kneeling: '닐링',
  floor: '플로어',
  overhead: '오버헤드',
  reverse: '리버스',
  alternate: '얼터네이트',
  alternating: '얼터네이팅',
  single: '싱글',
  one: '원',
  two: '투',
  double: '더블',
  close: '클로즈',
  wide: '와이드',
  narrow: '내로우',
  parallel: '패럴렐',
  neutral: '뉴트럴',
  grip: '그립',
  overhand: '오버핸드',
  underhand: '언더핸드',
  press: '프레스',
  pull: '풀',
  push: '푸시',
  raise: '레이즈',
  row: '로우',
  curl: '컬',
  extension: '익스텐션',
  pulldown: '풀다운',
  pullup: '풀업',
  pushup: '푸시업',
  pushdown: '푸시다운',
  fly: '플라이',
  flye: '플라이',
  lunge: '런지',
  squat: '스쿼트',
  deadlift: '데드리프트',
  plank: '플랭크',
  crunch: '크런치',
  'sit-up': '싯업',
  'push-up': '푸시업',
  'pull-up': '풀업',
  'chin-up': '친업',
  dip: '딥',
  dips: '딥스',
  shrug: '슈러그',
  kickback: '킥백',
  swing: '스윙',
  clean: '클린',
  jerk: '저크',
  snatch: '스내치',
  thruster: '스러스터',
  windmill: '윈드밀',
  goblet: '고블렛',
  pistol: '피스톨',
  sumo: '스모',
  hack: '핵',
  romanian: '루마니안',
  bulgarian: '불가리안',
  jefferson: '제퍼슨',
  zercher: '저처',
  preacher: '프리처',
  concentration: '컨센트레이션',
  hammer: '해머',
  spider: '스파이더',
  drag: '드래그',
  zottman: '조트만',
  tate: '테이트',
  arnold: '아놀드',
  bradford: '브래드포드',
  military: '밀리터리',
  upright: '업라이트',
  lateral: '레터럴',
  front: '프론트',
  rear: '리어',
  step: '스텝',
  'step-up': '스텝업',
  jump: '점프',
  hyperextension: '하이퍼익스텐션',
  mountain: '마운틴',
  climber: '클라이머',
  russian: '러시안',
  twist: '트위스트',
  flutter: '플러터',
  kicks: '킥',
  hanging: '행잉',
  straight: '스트레이트',
  inverted: '인버티드',
  muscle: '머슬',
  'pull-in': '풀인',
  calf: '카프',
  donkey: '동키',
  sissy: '시시',
  abduction: '어브덕션',
  adduction: '어덕션',
  hip: '힙',
  leg: '레그',
  arm: '암',
  shoulder: '숄더',
  chest: '체스트',
  back: '백',
  biceps: '바이셉스',
  triceps: '트라이셉스',
  glute: '글루트',
  quad: '쿼드',
  hamstring: '햄스트링',
  forearm: '포암',
  neck: '넥',
  good: '굿',
  morning: '모닝',
  run: '러닝',
  stationary: '고정식',
  bike: '바이크',
  rope: '로프',
  battle: '배틀',
  power: '파워',
  speed: '스피드',
  pike: '파이크',
  jackknife: '잭나이프',
  negative: '네거티브',
  oblique: '오블리크',
  plyo: '플라이오',
  superman: '슈퍼맨',
  diamond: '다이아몬드',
  clock: '클락',
  medicine: '메디신',
  ball: '볼',
  stability: '짐볼',
  bosu: '보수볼',
  sled: '슬레드',
  trap: '트랩',
  wheel: '휠',
  rollout: '롤아웃',
  rollerout: '롤러아웃',
  pullover: '풀오버',
  bent: '벤트',
  cross: '크로스',
  over: '오버',
  under: '언더',
  behind: '비하인드',
  knee: '무릎',
  stiff: '스티프',
  side: '사이드',
  rocking: '로킹',
  ab: '복근',
  abdominal: '복근',
  'v.': 'v.',
  'v.2': 'v.2',
};

// ─── 번역 함수 ───────────────────────────────────────────────────────────────

/** 운동명 번역: 직접 매핑 → 단어별 번역 */
export function translateExerciseName(englishName: string): string {
  if (!englishName) return englishName;
  const key = englishName.toLowerCase().trim();

  if (EXERCISE_NAME_KO[key]) return EXERCISE_NAME_KO[key];

  // 단어별 번역 fallback
  const words = englishName.split(/\s+/);
  const translated = words
    .map((w) => {
      const lower = w.toLowerCase().replace(/[()]/g, '');
      return WORD_MAP[lower] || w;
    })
    .join(' ');

  // 원문과 같으면 그대로 반환 (변환된 게 없으면 영어 유지)
  return translated === englishName ? englishName : translated;
}

export function translateBodyPart(bodyPart: string): string {
  return BODY_PART_KO[bodyPart.toLowerCase()] || bodyPart;
}

export function translateEquipment(equipment: string): string {
  return EQUIPMENT_KO[equipment.toLowerCase()] || equipment;
}

export function translateDifficulty(difficulty: string): string {
  return DIFFICULTY_KO[difficulty.toLowerCase()] || difficulty;
}

export function translateTarget(target: string): string {
  return TARGET_KO[target.toLowerCase()] || target;
}
